export const homeObjC = {
    id:'causes-section-data',
    title:'Our Causes',
    cardContentTitle:'Clean Water',
    cardContentBody:'After training a machine learning model you need to deploy it to show potential stakeholders what the results would look like With a decent UI, not jupyter notebook sto achieve any sort of buyback from the people/business that potentially want and can pay for this type of service.',
    cardActionsText:'Read More',
    cardActionsTextX:'Try Out the App',
    img:'https://d3q0oijmiduzg2.cloudfront.net/rubanzasilver/antelopes.jpeg',
    alt:'Clean water project',
    cardContentTitleB:'Youth & women empowerment',
    cardContentBodyB:'  Zigoti Coffee is a Ugandan coffee house that covers the whole value chain from growing, buying, processing, roasting, and export of Ugandan Coffee beans.',
    cardActionsTextB:'Learn more',
    imgB:'https://d3q0oijmiduzg2.cloudfront.net/rubanzasilver/ZICOFE.JPG',
    altB:'Zicofe.com',
    cardContentTitleC:'Fighting Disease',
    cardContentBodyC:'Suwik aims to be the leading exporter of the freshest, highest quality agricultural products with guaranteed customer satisfaction',
    cardActionsTextC:'Contribute to our cause',
    imgC:'https://d322abd807wvow.cloudfront.net/suwik-photos/suwikLogo.jpeg',
    altC:'Fighting disease',
};


export const homeObjZ = {
    id:'projects-section-data',
    title:'News & Features',
    cardContentTitle:'Suwik Investments Website',
    cardContentBody:'Suwik aims to be the leading exporter of the freshest, highest quality agricultural products with guaranteed customer satisfaction',
    cardActionsText:'Visit Site',
    cardActionsTextX:'See Code',
    img:'https://d3q0oijmiduzg2.cloudfront.net/rubanzasilver/antelopes.jpeg',
    alt:'Antelope Classfier Project',
    cardContentTitleA:'Personal Website',
    cardContentBodyA:'This website is built with reactjs.Follow the link below to check out the documentation.  ',
    cardActionsTextA:'See Code',
    imgA:'https://d3q0oijmiduzg2.cloudfront.net/rubanzasilver/faceShot.jpg',
    altA:'Rubanza Silver Personal website',
    cardContentTitleB:'Zigoti Coffee Website',
    cardContentBodyB:'  Zigoti Coffee is a Ugandan coffee house that covers the whole value chain from growing, buying, processing, roasting, and export of Ugandan Coffee beans.',
    cardActionsTextB:'Visit Zicofe.com',
    imgB:'https://d3q0oijmiduzg2.cloudfront.net/rubanzasilver/ZICOFE.JPG',
    altB:'Zicofe.com',
};